"$schema" = "https://starship.rs/config-schema.json"

[kotlin]
disabled = false

[java]
disabled = false

[gradle]
disabled = false

[python]
disabled = false

[nodejs]
disabled = false

[aws]
disabled = false

[lua]
disabled = false

[package]
disabled = false

[golang]
disabled = true

[hostname]
ssh_symbol = ""

[cmd_duration]
min_time = 60000

